# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BIALEDP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BIALEDP
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'
  # Pods for PodTest
  pod 'Fabric', '~> 1.8.2'
  pod 'Crashlytics', '~> 3.11.1'

  target 'BIALEDPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BIALEDPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
